name: CI
on:
  push:
    # Ignore non top-level branches.
    branches-ignore:
      - "*/**"
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
env:
  CARGO_TERM_COLOR: always
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'pantsbuild'
    runs-on: ubuntu-22.04
    steps:
      - name: Noop
        run: "true"

  build-13-x86-64:
    needs: org-check
    runs-on: macos-13
    env:
      PY: python3.9
      SCIE_PANTS_DEV_CACHE: .scie_pants_dev_cache
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          PANTS_BOOTSTRAP_GITHUB_API_BEARER_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            cargo run -p package -- --dest-dir dist/ scie
      - uses: actions/upload-artifact@v4
        with:
          name: scie-pants-x86-64
          path: dist/scie-pants-*

  run-10-15-x86-64:
    runs-on: macOS-10.15-X64
    needs: build-13
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: scie-pants-x86-64

      - run: "uname -a"
      - run: |
          PANTS_VERSION=2.23.0 dist/scie-pants-* version

  build-14-arm64:
    needs: org-check
    runs-on: macos-14
    env:
      PY: python3.9
      SCIE_PANTS_DEV_CACHE: .scie_pants_dev_cache
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          PANTS_BOOTSTRAP_GITHUB_API_BEARER_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            cargo run -p package -- --dest-dir dist/ scie
      - uses: actions/upload-artifact@v4
        with:
          name: scie-pants-arm64
          path: dist/scie-pants-*

  run-11-arm64:
    runs-on: macOS-11-ARM64
    needs: build-14-arm64
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: scie-pants-arm64

      - run: "uname -a"
      - run: |
          PANTS_VERSION=2.23.0 dist/scie-pants-* version
